name: "Build Samples"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        PROJECT: [01_hello_world, 02_layout, 03_input, 05_widgets]
        CONFIG: [Debug, Release]
    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run tiki_build
      working-directory: ${{github.workspace}}/samples/${{matrix.PROJECT}}
      run: ${{github.workspace}}/premake_tb.exe --to=build/vs2022 vs2022

    - name: Build
      working-directory: ${{github.workspace}}/samples/${{matrix.PROJECT}}/build/vs2022
      run: msbuild /m /p:Configuration=${{matrix.CONFIG}} ${{matrix.PROJECT}}.sln
